#include "DX12Format.h"
#include <windows.h>
#include <string>
#include <cwctype>
#include <cstring>
#include <cwchar>

const char* DX12FormatName(DXGI_FORMAT f)
{
    switch (f) {
#define F(x) case x: return #x;
    F(DXGI_FORMAT_UNKNOWN)
    F(DXGI_FORMAT_R32G32B32A32_TYPELESS) F(DXGI_FORMAT_R32G32B32A32_FLOAT) F(DXGI_FORMAT_R32G32B32A32_UINT) F(DXGI_FORMAT_R32G32B32A32_SINT)
    F(DXGI_FORMAT_R32G32B32_TYPELESS) F(DXGI_FORMAT_R32G32B32_FLOAT) F(DXGI_FORMAT_R32G32B32_UINT) F(DXGI_FORMAT_R32G32B32_SINT)
    F(DXGI_FORMAT_R16G16B16A16_TYPELESS) F(DXGI_FORMAT_R16G16B16A16_FLOAT) F(DXGI_FORMAT_R16G16B16A16_UNORM) F(DXGI_FORMAT_R16G16B16A16_UINT) F(DXGI_FORMAT_R16G16B16A16_SNORM) F(DXGI_FORMAT_R16G16B16A16_SINT)
    F(DXGI_FORMAT_R32G32_TYPELESS) F(DXGI_FORMAT_R32G32_FLOAT) F(DXGI_FORMAT_R32G32_UINT) F(DXGI_FORMAT_R32G32_SINT)
    F(DXGI_FORMAT_R32G8X24_TYPELESS) F(DXGI_FORMAT_D32_FLOAT_S8X24_UINT) F(DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS) F(DXGI_FORMAT_X32_TYPELESS_G8X24_UINT)
    F(DXGI_FORMAT_R10G10B10A2_TYPELESS) F(DXGI_FORMAT_R10G10B10A2_UNORM) F(DXGI_FORMAT_R10G10B10A2_UINT) F(DXGI_FORMAT_R11G11B10_FLOAT)
    F(DXGI_FORMAT_R8G8B8A8_TYPELESS) F(DXGI_FORMAT_R8G8B8A8_UNORM) F(DXGI_FORMAT_R8G8B8A8_UNORM_SRGB) F(DXGI_FORMAT_R8G8B8A8_UINT) F(DXGI_FORMAT_R8G8B8A8_SNORM) F(DXGI_FORMAT_R8G8B8A8_SINT)
    F(DXGI_FORMAT_R16G16_TYPELESS) F(DXGI_FORMAT_R16G16_FLOAT) F(DXGI_FORMAT_R16G16_UNORM) F(DXGI_FORMAT_R16G16_UINT) F(DXGI_FORMAT_R16G16_SNORM) F(DXGI_FORMAT_R16G16_SINT)
    F(DXGI_FORMAT_R32_TYPELESS) F(DXGI_FORMAT_D32_FLOAT) F(DXGI_FORMAT_R32_FLOAT) F(DXGI_FORMAT_R32_UINT) F(DXGI_FORMAT_R32_SINT)
    F(DXGI_FORMAT_R24G8_TYPELESS) F(DXGI_FORMAT_D24_UNORM_S8_UINT) F(DXGI_FORMAT_R24_UNORM_X8_TYPELESS) F(DXGI_FORMAT_X24_TYPELESS_G8_UINT)
    F(DXGI_FORMAT_R8G8_TYPELESS) F(DXGI_FORMAT_R8G8_UNORM) F(DXGI_FORMAT_R8G8_UINT) F(DXGI_FORMAT_R8G8_SNORM) F(DXGI_FORMAT_R8G8_SINT)
    F(DXGI_FORMAT_R16_TYPELESS) F(DXGI_FORMAT_R16_FLOAT) F(DXGI_FORMAT_D16_UNORM) F(DXGI_FORMAT_R16_UNORM) F(DXGI_FORMAT_R16_UINT) F(DXGI_FORMAT_R16_SNORM) F(DXGI_FORMAT_R16_SINT)
    F(DXGI_FORMAT_R8_TYPELESS) F(DXGI_FORMAT_R8_UNORM) F(DXGI_FORMAT_R8_UINT) F(DXGI_FORMAT_R8_SNORM) F(DXGI_FORMAT_R8_SINT) F(DXGI_FORMAT_A8_UNORM)
    F(DXGI_FORMAT_R1_UNORM) F(DXGI_FORMAT_R9G9B9E5_SHAREDEXP) F(DXGI_FORMAT_R8G8_B8G8_UNORM) F(DXGI_FORMAT_G8R8_G8B8_UNORM)
    F(DXGI_FORMAT_BC1_TYPELESS) F(DXGI_FORMAT_BC1_UNORM) F(DXGI_FORMAT_BC1_UNORM_SRGB) F(DXGI_FORMAT_BC2_TYPELESS) F(DXGI_FORMAT_BC2_UNORM) F(DXGI_FORMAT_BC2_UNORM_SRGB)
    F(DXGI_FORMAT_BC3_TYPELESS) F(DXGI_FORMAT_BC3_UNORM) F(DXGI_FORMAT_BC3_UNORM_SRGB) F(DXGI_FORMAT_BC4_TYPELESS) F(DXGI_FORMAT_BC4_UNORM) F(DXGI_FORMAT_BC4_SNORM)
    F(DXGI_FORMAT_BC5_TYPELESS) F(DXGI_FORMAT_BC5_UNORM) F(DXGI_FORMAT_BC5_SNORM)
    F(DXGI_FORMAT_B5G6R5_UNORM) F(DXGI_FORMAT_B5G5R5A1_UNORM) F(DXGI_FORMAT_B8G8R8A8_UNORM) F(DXGI_FORMAT_B8G8R8X8_UNORM)
    F(DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM) F(DXGI_FORMAT_B8G8R8A8_TYPELESS) F(DXGI_FORMAT_B8G8R8A8_UNORM_SRGB) F(DXGI_FORMAT_B8G8R8X8_TYPELESS) F(DXGI_FORMAT_B8G8R8X8_UNORM_SRGB)
    F(DXGI_FORMAT_BC6H_TYPELESS) F(DXGI_FORMAT_BC6H_UF16) F(DXGI_FORMAT_BC6H_SF16) F(DXGI_FORMAT_BC7_TYPELESS) F(DXGI_FORMAT_BC7_UNORM) F(DXGI_FORMAT_BC7_UNORM_SRGB)
    F(DXGI_FORMAT_AYUV) F(DXGI_FORMAT_Y410) F(DXGI_FORMAT_Y416) F(DXGI_FORMAT_NV12) F(DXGI_FORMAT_P010) F(DXGI_FORMAT_P016) F(DXGI_FORMAT_420_OPAQUE) F(DXGI_FORMAT_YUY2) F(DXGI_FORMAT_Y210) F(DXGI_FORMAT_Y216)
    F(DXGI_FORMAT_NV11) F(DXGI_FORMAT_AI44) F(DXGI_FORMAT_IA44) F(DXGI_FORMAT_P8) F(DXGI_FORMAT_A8P8) F(DXGI_FORMAT_B4G4R4A4_UNORM)
    F(DXGI_FORMAT_P208) F(DXGI_FORMAT_V208) F(DXGI_FORMAT_V408) F(DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE) F(DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE)
#undef F
    default: return "DXGI_FORMAT_UNKNOWN";
    }
}

DXGI_FORMAT DX12ParseFormat(const wchar_t* text)
{
    if (!text) return DXGI_FORMAT_UNKNOWN;
    std::wstring s(text);
    while (!s.empty() && iswspace(s.front())) s.erase(s.begin());
    while (!s.empty() && iswspace(s.back())) s.pop_back();
    if (s.size() > 12 && s.compare(0, 12, L"DXGI_FORMAT_") == 0) s = s.substr(12);
    for (int i = 0; i <= static_cast<int>(DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE); ++i) {
        const char* n = DX12FormatName(static_cast<DXGI_FORMAT>(i));
        if (!n || !strcmp(n, "DXGI_FORMAT_UNKNOWN")) continue;
        std::string a(n + 12);
        int len = MultiByteToWideChar(CP_UTF8, 0, a.c_str(), -1, nullptr, 0);
        std::wstring w(len ? len : 1, L'\0');
        if (len) {
            MultiByteToWideChar(CP_UTF8, 0, a.c_str(), -1, &w[0], len);
            w.resize(len - 1);
        } else {
            w.clear();
        }
        if (!_wcsicmp(w.c_str(), s.c_str())) return static_cast<DXGI_FORMAT>(i);
    }
    wchar_t* end = nullptr;
    unsigned long value = wcstoul(s.c_str(), &end, 0);
    if (end && !*end) return static_cast<DXGI_FORMAT>(value);
    return DXGI_FORMAT_UNKNOWN;
}

UINT DX12FormatSize(DXGI_FORMAT f)
{
    switch (f) {
    case DXGI_FORMAT_R32G32B32A32_TYPELESS: case DXGI_FORMAT_R32G32B32A32_FLOAT: case DXGI_FORMAT_R32G32B32A32_UINT: case DXGI_FORMAT_R32G32B32A32_SINT: return 16;
    case DXGI_FORMAT_R32G32B32_TYPELESS: case DXGI_FORMAT_R32G32B32_FLOAT: case DXGI_FORMAT_R32G32B32_UINT: case DXGI_FORMAT_R32G32B32_SINT: return 12;
    case DXGI_FORMAT_R16G16B16A16_TYPELESS: case DXGI_FORMAT_R16G16B16A16_FLOAT: case DXGI_FORMAT_R16G16B16A16_UNORM: case DXGI_FORMAT_R16G16B16A16_UINT: case DXGI_FORMAT_R16G16B16A16_SNORM: case DXGI_FORMAT_R16G16B16A16_SINT:
    case DXGI_FORMAT_R32G32_TYPELESS: case DXGI_FORMAT_R32G32_FLOAT: case DXGI_FORMAT_R32G32_UINT: case DXGI_FORMAT_R32G32_SINT: return 8;
    case DXGI_FORMAT_R10G10B10A2_TYPELESS: case DXGI_FORMAT_R10G10B10A2_UNORM: case DXGI_FORMAT_R10G10B10A2_UINT: case DXGI_FORMAT_R11G11B10_FLOAT:
    case DXGI_FORMAT_R8G8B8A8_TYPELESS: case DXGI_FORMAT_R8G8B8A8_UNORM: case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB: case DXGI_FORMAT_R8G8B8A8_UINT: case DXGI_FORMAT_R8G8B8A8_SNORM: case DXGI_FORMAT_R8G8B8A8_SINT:
    case DXGI_FORMAT_R16G16_TYPELESS: case DXGI_FORMAT_R16G16_FLOAT: case DXGI_FORMAT_R16G16_UNORM: case DXGI_FORMAT_R16G16_UINT: case DXGI_FORMAT_R16G16_SNORM: case DXGI_FORMAT_R16G16_SINT:
    case DXGI_FORMAT_R32_TYPELESS: case DXGI_FORMAT_D32_FLOAT: case DXGI_FORMAT_R32_FLOAT: case DXGI_FORMAT_R32_UINT: case DXGI_FORMAT_R32_SINT:
    case DXGI_FORMAT_B8G8R8A8_UNORM: case DXGI_FORMAT_B8G8R8X8_UNORM: case DXGI_FORMAT_B8G8R8A8_TYPELESS: case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB: case DXGI_FORMAT_B8G8R8X8_TYPELESS: case DXGI_FORMAT_B8G8R8X8_UNORM_SRGB: return 4;
    case DXGI_FORMAT_R8G8_TYPELESS: case DXGI_FORMAT_R8G8_UNORM: case DXGI_FORMAT_R8G8_UINT: case DXGI_FORMAT_R8G8_SNORM: case DXGI_FORMAT_R8G8_SINT:
    case DXGI_FORMAT_R16_TYPELESS: case DXGI_FORMAT_R16_FLOAT: case DXGI_FORMAT_D16_UNORM: case DXGI_FORMAT_R16_UNORM: case DXGI_FORMAT_R16_UINT: case DXGI_FORMAT_R16_SNORM: case DXGI_FORMAT_R16_SINT:
    case DXGI_FORMAT_B5G6R5_UNORM: case DXGI_FORMAT_B5G5R5A1_UNORM: return 2;
    case DXGI_FORMAT_R8_TYPELESS: case DXGI_FORMAT_R8_UNORM: case DXGI_FORMAT_R8_UINT: case DXGI_FORMAT_R8_SNORM: case DXGI_FORMAT_R8_SINT: case DXGI_FORMAT_A8_UNORM: return 1;
    default: return 0;
    }
}
